### ISSUE TITLE
reversal of IGSO(3)

### ISSUE THREAD

**Issue by nininimingerjian** [RosettaCommons/RFdiffusion#129]
Great work! Learn a lot from it.  However, some questions  confuse me. I wonder why there is $r_t^T$ in discretized reverse process, this lead to offset $r^t$ in the score. $r_t^Tr_t$=I.
![image](https://github.com/RosettaCommons/RFdiffusion/assets/98312009/6516b00a-fa5d-4f5d-bdf7-fce3fcb7a4ae)

**Comment by blt2114** [comment]
Hi @nininimingerjian, Thanks for the question!

Please take a look at the updated supplementary material for the paper [here](https://www.nature.com/articles/s41586-023-06415-8), in we give a more complete description of how the discretized reverse process is simulated based on a geodesic random walk (GRW).

Note that these two descriptions (the one you've posted looks like its from the older biorxiv supplement) of the sampling steps disagree up to discretization error on the order of about $\sigma_t^2 - \sigma_{t-1}^2$ (since the tangent Gaussian used in the GRW and IGSO3 are only equivalent in the limit where this step size goes to zero).

But I'm happy to give an explanation for this earlier equation in any case:

The term involving the matrix exponential (exp{ $r^{(t)T} \nabla_{r^{(t)}} \log q(x^{(t)})$ } ) may be thought of as a rotationally _invariant_ perturbation to the rotation matrix $r^{(t)}.$  It determines how the location parameter of the IGSO3 distribution is updated from $r^{(t)}$ by rotating about an axis defined in a locally defined coordinate frame of a given residue.  It is the quantity computed [here in the code](https://github.com/RosettaCommons/RFdiffusion/blob/main/rfdiffusion/inference/utils.py#L67).

By contrast, the score $\nabla_{r^{(t)}} \log q(x^{(t)})$ is equivariant, i.e. if $\tilde x^{(t)}=R* x^{(t)}$ represents the whole backbone $x^{(t)}$ rotated by $R$, then $\nabla_{r^{(t)}} \log q(\tilde x^{(t)})=R \nabla_{r^{(t)}} \log q(x^{(t)})$.  The leading $r^{(t)T}$ therefore ensures that $r^{(t)T} \nabla_{r^{(t)}} \log q(x^{(t)})$ is invariant.

To see that this equation matches the geodesic random walk formulation in the Nature supplement, you can note that since for any rotation matrix $R$ and 3x3 matrix $A$ , we have exp($R A R^{T}$) = $R$ exp($A$) $R^{T}$ . So, 
$r^{(t)}$ exp{ $r^{(t)T} \nabla_{r^{(t)}} \log q(x^{(t)})$ } = exp{ $\nabla_{r^{(t)}} \log q(x^{(t)})r^{(t)T}$  }  $r^{(t)}$ .
And, when $\sigma_t^2 - \sigma_{t-1}^2$ is small we have 
exp { $(\sigma_t^2 - \sigma_{t-1}^2) \nabla_{r^{(t)}} \log q(x^{(t)}) r^{(t)T}$ }  $r^{(t)} =  r^{(t)}  + (\sigma_t^2 - \sigma_{t-1}^2)\nabla_{r^{(t)}} \log q(x^{(t)}) + O((\sigma_t^2 - \sigma_{t-1}^2)^2),$
which is the mean of the geodesic random walk step up to an $O((\sigma_t^2 - \sigma_{t-1}^2)^2)$ error.

For a more in technically detailed derivation of the underlying diffusion process we have used here, you might also take a look at a [this paper](https://arxiv.org/abs/2302.02277), where the connections to Riemannian score based generative models and Geodesic are more explicitly fleshed out.

Happy to try and clarify further if questions remain,
Brian
