### ISSUE TITLE
Symmetric Motif Scaffolding

### ISSUE THREAD

**Issue by LaurinLang** [RosettaCommons/RFdiffusion#133]
Does symmetric motif scaffolding require the motif to be on one chain of the input motif-pdb? 
It also seems to move the motif as close to the origin as it can even when the original motif was quite some distance away "radially".
Is it possible to keep the original distance of the motif from the symmetry axis ?

**Comment by davidcjuergens** [comment]
Hi Laurin, 

Does your input pdb contain a symmetrized version of your motif? The code centers anything that is a motif at the origin, so if you only have the asymmetric unit of the motif in your pdb file then it will go straight to the origin. However, if you have a symmetrized version (e.g., for C4, you've copied your motif 4 times around z axis consistent with C4 point group) your motif chunks will no longer be on top of the origin because their center of mass will be on their axis of symmetry.

**Comment by thomas-tugwell** [comment]
I think I may also be running into this issue where the motif is supplied and is pre-symmetrized. However, the relative orientation of the symmetrized subunits is changed from what I supplied. There seems to be rotation around the x (or y?) axis that keeps them symmetric, but not in the intended scaffold I need to keep it in. @LaurinLang did you figure out a workaround?
