### ISSUE TITLE
Google Colab notebook not working

### ISSUE THREAD

**Issue by SebastianMiles** [RosettaCommons/RFdiffusion#174]
Hi, i've been using the colab notebook for a couple of weeks now, but since the last Thursday it doesn't work anymore

There are several errors when running the setup

Thanks in advance

**Comment by danielguion** [comment]
I am also having the issue you mentioned.

**Comment by xinran1129305** [comment]
Hi there. How did you solve this problem?

**Comment by sokrypton** [comment]
Please use the latest notebook.
https://colab.research.google.com/github/sokrypton/ColabDesign/blob/main/rf/examples/diffusion.ipynb

v1.1.1 is no longer working due to cuda12 updates in Google colab.


I'll see if I can back-edit a tagged version of the notebook.

**Comment by xinran1129305** [comment]
Thanks:)-------- 原始邮件 --------发件人： Sergey O ***@***.***>日期： 2023年12月19日周二 21:11收件人： RosettaCommons/RFdiffusion ***@***.***>抄送： xinran1129305 ***@***.***>, Comment ***@***.***>主    题： Re: [RosettaCommons/RFdiffusion] Google Colab notebook not working (Issue #174)
Please use the latest notebook.

https://colab.research.google.com/github/sokrypton/ColabDesign/blob/main/rf/examples/diffusion.ipynb



v1.1.1 is no longer working due to cuda12 updates in Google colab.





I'll see if I can back-edit a tagged version of the notebook.



On Tue, Dec 19, 2023, 7:57 AM xinran1129305 ***@***.***>

wrote:

**Comment by sokrypton** [comment]
I've now back-edited v1.1.1 to fix the cuda version. So user can still use the old link.
