### ISSUE TITLE
Compatibility issues when creating conda env

### ISSUE THREAD

**Issue by jeeberhardt** [RosettaCommons/RFdiffusion#3]
This is really amazing!

Not sure what I am doing wrong, but  `conda` is telling me that it found some conflicts when creating the environment. So I removed the constraints, changed the channel from `defaults` to `conda-forge` and it solved my issue:

```
name: SE3nv
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit
  - dgl-cuda11.1
  - pip
  - pip:
    - hydra-core
    - pyrsistent
    - icecream
```

Not sure neither if this is the way to go but seems to have worked for me! And all the examples I tried so far are running smoothly.

Computer config:
- Ubuntu 22.04.2 LTS, 32,0 GiB
- AMD® Ryzen 9 5900x 12-core processor × 24
- NVIDIA Corporation GA102 [GeForce RTX 3080]

... again amazing!

**Comment by Samuel-gwb** [comment]
Yes, amazing !

**Comment by nrbennet** [comment]
Thanks for pointing out this issue! We have added conda-forge to the channels in the .yml file.

If removing the CUDA constraints works for you and the examples are running on your GPU, then great! The exact .yml settings regarding CUDA will vary for each user depending on what GPU they are using. We are going to leave the constraints on the CUDA specification since they work on a wide variety of GPUs in our hands.

We're glad you're enjoying using RFdiffusion!
