### ISSUE TITLE
Problem Hydra arguments on windows conda

### ISSUE THREAD

**Issue by remybonnav** [RosettaCommons/RFdiffusion#60]
I found out after several failures to run the inference script that on Windows when running the inference script, if one use
 'contigmap.contigs=[B1-100/0 100-100]' 
or 'ppi.hotspot_res=[A30,A33,A34]' , it will not work.
One need to use " and not '   around the arguments otherwise the arguments are not correctly parsed and it raises an error.
eg..  'contigmap.contigs=[B1-100/0 100-100]'  becomes  "contigmap.contigs=[B1-100/0 100-100]"

Not sure if this is because the default language of my windows is not english

**Comment by roccomoretti** [comment]
The quotes on the commandline are actually being used by your shell/command line interface, rather than RFDiffusion or Hydra.

The Unix-like convention is to use the single quote to mean "this, exactly as-is, without any shell substitution magic", which is needed to keep Bash, etc. from messing up the square brackets. In contrast, double quotes allows the shell to do some but not all substitution magic. (I think you're mostly okay here, but on Unix/Bash you're safer with the single quotes.)

I'm not sure which shell you're using, and why it might be having issues. It sounds like Powershell uses (more or less) [the same rules as Bash](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3).

Another potential issue is the _type_ of quote characters you're using. For this to work you'd need to use regular plain ASCII apostrophe/single quote marks. Unicode has additional variants, which look almost but not quite the same - if you're using "smart quotes" or other non-ASCII single quote/apostrophe marks, then it won't work properly.

**Comment by remybonnav** [comment]
Ok, thanks for the explanations.
 I am using the anaconda PowerShell that comes with Anaconda.
