### ISSUE TITLE
How to design a dimer enzyme

### ISSUE THREAD

**Issue by Lyang556** [RosettaCommons/RFdiffusion#76]
There are some proteins that need to form a dimer to function as an enzyme, how to design these enzymes

**Comment by joewatchwell** [comment]
If you have a structure of an active site, you could try building a heterodimer around that site. E.g. if the first half of the active site was residues A1-5, and the second half A6-10, you could do a contig like:
[50-100/A1-5/50-100/0 50-100/A6-10/50-100]. This would build a heterodimer (two chains because of the "0 ") with 50-100 residues added either side of each half of the enzyme. Good luck!

**Comment by Lyang556** [comment]
@joewatchwell 
What if the active site is in both chains? For example, the first half of the active site is in chain-A and the second half is in chain-E. 
My command is this :

`'contigmap.contigs=[5-10/A8-8/2-3/A11-11/10-12/A23-23/50-60/A82-82/20-40/0 5-10/E8-8/2-3/E11-11/10-12/E23-23/50-60/E82-82/20-40]' potentials.guide_scale=1'potentials.guiding_potentials ["type:substrate_contacts,s:1,r_0:8,rep_r_0:5.0,rep_s:2,rep_r_min:1"]'`
potentials.substrate=4BW inference.ckpt_override_path=${ckpt}`

This only produces one chain, not a heterodimer.
